config/routes.rb
Brianbauer::Application.routes.draw do
  
  resources :case_studies

  resources :categories

  resources :tags
  
  resources :work

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "welcome#index"
  match '/email' => 'welcome#send_mail'
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/case_study.rb
class CaseStudy < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/case_studies_controller.rb
class CaseStudiesController < InheritedResources::Base
  def index
    @case_studies = CaseStudy.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @case_studies }
    end
  end

  def show
    @case_study = CaseStudy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @case_study }
    end
  end

  def new
    @case_study = CaseStudy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @case_study }
    end
  end

  def edit
    @case_study = CaseStudy.find(params[:id])
  end

  def create
    @case_study = CaseStudy.new(params[:list])

    respond_to do |format|
      if @case_study.save
        format.html { redirect_to(@case_study, :notice => 'CaseStudy was successfully created.') }
        format.xml  { render :xml => @case_study, :status => :created, :location => @case_study }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @case_study.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @case_study = CaseStudy.find(params[:id])

    respond_to do |format|
      if @case_study.update_attributes(params[:case_study])
        format.html { redirect_to(@case_study, :notice => 'CaseStudy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @case_study.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @case_study = CaseStudy.find(params[:id])
    @case_study.destroy

    respond_to do |format|
      format.html { redirect_to(lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
end

app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
  end
  def send_mail
    Emails.deliver_contactme(params[:email])
    flash[:notice] = "Email was sent successfully."
    redirect_to root_path
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController

  def index
    @articles = Article.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:list])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case_studies_helper.rb
module CaseStudiesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def icons(article)
    icons = []
    icons << "rails" + "\n" if article.rails == "yes"
    icons << "php" + "\n" if article.php == "yes"
    icons << "asp" + "\n" if article.asp == "yes"
    icons << "css" + "\n" if article.css3 == "yes"
    icons << "html" + "\n" if article.html5 == "yes"
    icons << "haml" + "\n" if article.haml == "yes"
    icons << "sass" + "\n" if article.sass == "yes"
    icons << "jquery" + "\n" if article.jquery == "yes"
    icons << "mootools" + "\n" if article.mootools == "yes"
    icons
  end 
end

app/helpers/work_helper.rb
module WorkHelper
  def icons(article)
    icons = []
    icons << "rails" + "\n" if article.rails == "yes"
    icons << "php" + "\n" if article.php == "yes"
    icons << "asp" + "\n" if article.asp == "yes"
    icons << "css" + "\n" if article.css3 == "yes"
    icons << "html" + "\n" if article.html5 == "yes"
    icons << "haml" + "\n" if article.haml == "yes"
    icons << "sass" + "\n" if article.sass == "yes"
    icons << "jquery" + "\n" if article.jquery == "yes"
    icons << "mootools" + "\n" if article.mootools == "yes"
    icons
  end
end

app/views/case_studies/_form.html.erb
<%= form_for(@case_study) do |f| %>
  <% if @case_study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case_study.errors.count, "error") %> prohibited this case_study from being saved:</h2>

      <ul>
      <% @case_study.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/case_studies/edit.html.erb
<h1>Editing case_study</h1>

<%= render 'form' %>

<%= link_to 'Show', @case_study %> |
<%= link_to 'Back', case_studies_path %>

app/views/case_studies/index.haml
%nav
  %ul#navigation.interior
    %li
      %a{:href => '/'} Home
    %li
      %a{:class => 'on', :href => '/case_studies'} Case Studies
    %li
      %a{:class => 'last', :href => '#contact_header'} Contact Me
%header.panel.interior
%section#work.panel.interior
  .header
  .content.interior 
    #articles
      - @case_studies.each do |study|
        %article
          %a{:class => "view", :href => "/case_studies/#{study.slug}"}
            View Project
          = image_tag("#{study.image03.blank? ? "/images/work-blank-thumb.png" : study.image03}", :alt => "#{study.name}")
          %h3 
            = study.name

app/views/case_studies/new.html.erb
<h1>New case_study</h1>

<%= render 'form' %>

<%= link_to 'Back', case_studies_path %>

app/views/case_studies/show.haml
%nav
  %ul#navigation.interior
    %li
      %a{:href => '/'} Home
    %li
      %a{:href => '/case_studies'} Case Studies
    %li
      %a{:class => 'last', :href => '#contact_header'} Contact Me
%header.panel.interior
%section#work.panel.interior
  .header
  .content.interior
    %h2= @case_study.name
    .case_study= @case_study.content.html_safe
    

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.text_field :article_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Article</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.article_id %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Article:</b>
  <%= @category.article_id %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title Brian Bauer - Web Development & Design
    %link{:rel=>'stylesheet',:href=>'/stylesheets/screen.css',:media=> 'all',:type => 'text/css'}
    %link{:rel=>'stylesheet',:href=>'http://fonts.googleapis.com/css?family=Dancing+Script:400,700&v2',:media=> 'all',:type => 'text/css'}
    %script{:type => "text/javascript", :src  => "http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"}
    %script{:type => "text/javascript", :src  => "/javascripts/jquery.scrollTo-min.js"}
    %script{:type => "text/javascript", :src  => "/javascripts/shadowbox.js"}
    /[if lt IE 9]
      %script{:type => "text/javascript", :src  => "http://html5shim.googlecode.com/svn/trunk/html5.js"}
    :javascript
      $(document).ready(function(){
        $('#navigation, #about').localScroll({ duration:300 });
        $('#navigation a').click(function(){
          $('#navigation a').removeClass("on");
          $(this).addClass("on");
        });
        Shadowbox.init();
      });	
  %body#home
    = yield
    #contact_header
    %section#contact.panel
      .content
        %h2 Contact Me
        - form_tag('/email', :id => 'contact_form') do
          = label :email, :name, "Name:"
          = text_field :email, :name
          %br/
          = label :email, :address, "Email:"
          = text_field :email, :address, :class => 'required email'
          %br/
          = label :email, :subject, "Subject:"
          = text_field :email, :subject
          %br/
          = text_area :email, :body, :rows => 8, :cols => 50
          %br/
          = submit_tag "Send", :id => 'submit_email'
    %footer#footer.panel
      .content
        %p#say-hi
          All content &copy; 2011 Brian Bauer
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-6162531-2']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/welcome/index.haml
%nav
  %ul#navigation
    %li
      %a{:class => 'on', :href => '#home'} Home
    %li
      %a{:href => '#about'} About
    %li
      %a{:href => '#work'} Work
    %li
      %a{:class => 'last', :href => '#contact_header'} Contact Me
%header.panel
  .content
    %h1
      %span Hello. 
      I Make Websites
    = image_tag('intro-banner-shade.png', :alt => 'The Work of Brian Bauer')
%section#about.panel
  .header
  .content
    .h2
      %h2 
        Who Am I?
      = image_tag('ui-about-trans.png', :alt => 'Design + Code = Awesome!')
    .abstract
      %p 
        %strong I'm Brian Bauer
      %p 
        I'm a designer and 
        %em Ruby on Rails 
        developer striving to create beautiful user-interfaces backed by beautiful code.  I live and work in Bend, OR, where I try to sneak 
        %em HTML5
        and
        %em CSS3
        in when possible and love working with
        %em SASS
        and
        %em HAML.
      %ul
        %li 503-360-7651
        %li
          %a{:href => "#contact"} 
            %strong Get in touch
%section#work.panel
  .header
  .content
    %h2 The Work
    #articles
      - @articles.each do |article|
        %article
          %a{:class => "view", :href => "/images/#{article.screenshot}", :rel => "shadowbox"}
            View Screenshot
          = image_tag("#{article.thumb.blank? ? "/images/work-blank-thumb.png" : article.thumb}", :alt => "#{article.title}")
          %h3 
            = article.title
            %br/
            %a{:href => "#{article.url}"}
              View Project
          .icons
            - icons(article).each do |icon|
              %div{:class => "icon #{icon}"}
    %ul
      %li.title Tech Key:
      %li.ruby
        Ruby/Rails
      %li.css
        CSS3
      %li.sass
        SASS
      %li.html
        HTML5
      %li.haml
        HAML
      %li.jquery
        jQuery
      %li.mootools
        MooTools
      %li.php
        PHP
      %li.asp.last
        ASP

app/views/work/show.haml
%nav
  %ul#navigation.interior
    %li
      %a{:class => 'on', :href => '/'} Home
    %li
      %a{:class => 'last', :href => '#contact_header'} Contact Me
%header.panel.interior
%section#work.panel.interior
  .header
  .content.interior
    %h2= @article.title
    = image_tag("#{@article.screenshot}", :alt => "#{@article.title}")
    %article
      .icons
        - icons(@article).each do |icon|
          %div{:class => "icon #{icon}"}
    %p= @article.description
    %ul
      %li.title Tech Key:
      %li.ruby
        Ruby/Rails
      %li.css
        CSS3
      %li.sass
        SASS
      %li.html
        HTML5
      %li.haml
        HAML
      %li.jquery
        jQuery
      %li.mootools
        MooTools
      %li.php
        PHP
      %li.asp.last
        ASP